name: CI/CD Pipeline
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create target folder
      run: mkdir cloned_content
      
    - name: Copy files (excluding target folder)
      run: |
        robocopy . cloned_content /E /XD .github cloned_content /NFL /NDL /NJH /NJS /nc /ns /np
        
    - name: List copied files
      run: dir cloned_content